apiVersion: v1
kind: Service
metadata:
  name: temporal
  labels:
    {{- include "swarm-reasoning.labels" . | nindent 4 }}
    app.kubernetes.io/name: temporal
spec:
  type: ClusterIP
  ports:
    - port: 7233
      targetPort: 7233
      protocol: TCP
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/instance: {{ .Release.Name }}
